packages:
  - apps/*
  - packages/*
catalog:
  "@radix-ui/react-slot": ^1.1.0
  "@types/node": ^20
  "@types/react": ^18.3.1
  "@types/react-dom": ^18.3.1
  "@vchikalkin/eslint-config-awesome": ^2.0.5
  autoprefixer: ^10.4.20
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  eslint: ^9.15.0
  eslint-plugin-tailwindcss: ^3.17.5
  eslint-plugin-turbo: ^2.3.0
  husky: ^9.1.7
  lint-staged: ^15.2.10
  lucide-react: ^0.462.0
  next: ^15.0.3
  postcss: ^8.4.49
  postcss-load-config: ^6.0.1
  prettier: ^3.2.5
  react: 19.0.0-rc-5c56b873-20241107
  react-dom: 19.0.0-rc-5c56b873-20241107
  tailwind-merge: ^2.5.5
  tailwindcss: ^3.4.15
  tailwindcss-animate: ^1.0.7
  turbo: ^2.3.2
  typescript: 5.5.4
